export const DataProperti = [
  {
    id: '1',
    imgData: 'https://images.unsplash.com/photo-1618220179428-22790b461013?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=327&q=80',
    title: 'Living Room',
    titletype: 'Living Room type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '2',
    imgData: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    title: 'Living Room',
    titletype: 'Living Room type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '3',
    imgData: 'https://images.unsplash.com/photo-1585264550248-1778be3b6368?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=463&q=80',
    title: 'Living Room',
    titletype: 'Living Room type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '4',
    imgData: 'https://images.unsplash.com/photo-1589911057719-81914cd42d3d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGtpdGNoZW4lMjBzZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    title: 'Kitchen Set',
    titletype: 'Kitchen Set type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '5',
    imgData: 'https://images.unsplash.com/photo-1585821570368-53a593a002be?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    title: 'Kitchen Set',
    titletype: 'Kitchen Set type 2',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '6',
    imgData: 'https://images.unsplash.com/photo-1620641622776-c1058b851a4e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGtpdGNoZW4lMjBzZXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60',
    title: 'Kitchen Set',
    titletype: 'Kitchen Set type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '7',
    imgData: 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    title: 'Bedroom',
    titletype: 'Bedroom type 1',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '8',
    imgData: 'https://images.unsplash.com/photo-1583845112203-29329902332e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80',
    title: 'Bedroom',
    titletype: 'Bedroom type 2',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
  {
    id: '9',
    imgData: 'https://images.unsplash.com/photo-1588046130717-0eb0c9a3ba15?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=486&q=80',
    title: 'Bedroom',
    titletype: 'Bedroom type 3',
    price: '10.000.000',
    ket: 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quos temporibus omnis quaerat ea ipsam, maxime nam assumenda nihil corrupti, placeat quod consequuntur consectetur rerum, sit officia reprehenderit blanditiis voluptate sint?',
  },
];
