import img1 from './img/Rumah-1.png';
import img2 from './img/rumah-2.png';
import img3 from './img/rumah-3.png';
import img4 from './img/rumah-4.png';
import img5 from './img/rumah-5.png';
import img6 from './img/rumah-5.png';
export const dataJualRumah = [
  {
    id: 'J01',
    title: 'Rumah Tipe Satu',
    tipe: '1 Lantai',
    imgUrl: img1,
    harga: 'IDR.200.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '360m',
  },
  {
    id: 'J02',
    title: 'Rumah Tipe Dua',
    tipe: '1 Lantai',
    imgUrl: img2,
    harga: 'IDR.250.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '380m',
  },
  {
    id: 'J03',
    title: 'Rumah Tipe Tiga',
    tipe: '3 Lantai',
    imgUrl: img3,
    harga: 'IDR.300.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '400m',
  },
  {
    id: 'J04',
    title: 'Rumah Tipe Empat',
    tipe: '3 Lantai',
    imgUrl: img4,
    harga: 'IDR.320.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '430m',
  },
  {
    id: 'J05',
    title: 'Rumah Tipe Lima',
    tipe: '2 Lantai',
    imgUrl: img5,
    harga: 'IDR.350.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '450m',
  },
  {
    id: 'J06',
    title: 'Rumah Tipe Enam',
    tipe: '2 Lantai',
    imgUrl: img6,
    harga: 'IDR.390.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'JUAL',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '490m',
  },

  {
    id: 'S01',
    title: 'Rumah Sewa Tipe Satu',
    tipe: '1 Lantai',
    imgUrl: img1,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '360m',
  },
  {
    id: 'S02',
    title: 'Rumah Sewa Tipe Dua',
    tipe: '2 Lantai',
    imgUrl: img2,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '380m',
  },
  {
    id: 'S03',
    title: 'Rumah Sewa Tipe Tiga',
    tipe: '2 Lantai',
    imgUrl: img3,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '400m',
  },
  {
    id: 'S04',
    title: 'Rumah Sewa Tipe Empat',
    tipe: '1 Lantai',
    imgUrl: img4,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '430m',
  },
  {
    id: 'S05',
    title: 'Rumah Sewa Tipe Lima',
    tipe: '1 Lantai',
    imgUrl: img5,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '450m',
  },
  {
    id: 'S06',
    title: 'Rumah Sewa Tipe Enam',
    tipe: '1 Lantai',
    imgUrl: img6,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '490m',
  },
  {
    id: 'S07',
    title: 'Rumah Tipe Enam',
    tipe: '1 Lantai',
    imgUrl: img6,
    harga: 'IDR 1.000.000',
    alamat: 'JL. Moch Kafi II Cipedak, Jagakarsa, Jakarta Selatan',
    ket: 'SEWA',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi explicabo fuga at sed maxime repudiandae adipisci culpa eos accusantium voluptates voluptatibus fugit facilis qui quos, sit quasi dolores optio nostrum?',
    jumlahkt: '3',
    jumlahkm: '4',
    luasrumah: '490m',
  },
];

export const dataCard = [
  {
    iconUrl: '',
    title: 'Property Baru',
    deskripsi: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Est ac risus mauris id aliquam aliquam commodo bibendum.',
  },
];
